esphome:
  name: thermo2
  platform: ESP32
  board: nodemcu-32s
  platformio_options:
     upload_speed: 1500000

wifi:
  ssid: "test"
  password: "12345678"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "thermo2 Fallback Hotspot"
    password: "12345678"
    
  reboot_timeout: 0s
#  power_save_mode: HIGH

captive_portal:

# Enable logging
logger:
  level: DEBUG
    
# Enable Home Assistant API
api:

ota:

# Активация web сервера
web_server:
  port: 80

globals:
   - id: counter_min
     type: int
     restore_value: no
     initial_value: '0'
   #device_mode: -1 - инициализация, 0 - разогрев, 1- кипячение 130, 2 - поддержание 80
   - id: device_mode
     type: int
     restore_value: no
     initial_value: '-1'

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 50ms
    name: "Switch button"

font:
  - file: "tahoma.ttf"   
    id: my_font
    size: 26                
  - file: "tahoma.ttf"   
    id: my_font_s
    size: 10   
spi:
  clk_pin: GPIO21
  mosi_pin: GPIO22
  
display:
  - platform: ST7920_spi
    reset_pin: GPIO19
    cs_pin: GPIO2
    id: my_display
    lambda: |-
        it.printf(0, 14, id(my_font), "%02d:%02d", id(counter_min) / 60, id(counter_min) % 60);
        
        if (id(device_mode) == 0 )    
            it.print(74, 3, id(my_font_s), "HEATING");
        if (id(device_mode) == 1  )    
            it.print(74, 3, id(my_font_s), "BOILING");
        if (id(device_mode) == 2  )    
            it.print(74, 3, id(my_font_s), "WAITING");
        
        if (id(relay1).state)
        {
            it.filled_rectangle(70, 16, 20, 9);
            it.print(77, 14, id(my_font_s), COLOR_OFF, "1");
        }
        if (id(relay2).state)
        {
            it.filled_rectangle(100, 16, 20, 9);
            it.print(107, 14, id(my_font_s), COLOR_OFF, "2");
        }
        
            
        it.printf(1, 45, id(my_font), "%3.0f°C", id(temp_1).state);
        
        it.print(90, 34, id(my_font_s), "Target:");
        
        if (id(relay1).state && id(device_mode) > 0)
            it.printf(90, 52, id(my_font_s), "%3.0f°C", id(regul).target_temperature_high);
        else
            it.printf(90, 52, id(my_font_s), "%3.0f°C", id(regul).target_temperature_low);

dallas:
  - pin: GPIO32
    update_interval: 10s

# Individual sensors
sensor:   
  - platform: uptime
    name: Uptime Sensor
    update_interval: 5min
  - platform: dallas
    name: "Temperature #1"
    address: 0xB4041590482EFF28
    id: temp_1
  - platform: adc
    attenuation: 0db
    pin: GPIO36
    id: adc_sensor
    update_interval: never

switch:
  - platform: gpio
    pin: GPIO33
    id: ntc_vcc
  - platform: gpio
    pin:
       number: GPIO13
       inverted: true
    id: relay1
  - platform: gpio
    pin:
       number: GPIO15
       inverted: true
    id: relay2

interval:
  - interval: 30s
    then:
      - switch.turn_on: ntc_vcc
      - component.update: adc_sensor
      - switch.turn_off: ntc_vcc
  - interval: 1min
    then:
      - lambda: |-
            id(counter_min) += 1;
            if (id(device_mode) == -1 )
            {
                id(device_mode) = 0;
                id(regul).target_temperature_low = 27;
                id(regul).target_temperature_high = 29;
                id(relay2).turn_on();
                id(counter_min) = 0;
            }
            if (id(device_mode) == 0 )
            {
                if (id(temp_1).state > id(regul).target_temperature_low)
                {
                    id(device_mode) = 1;
                    id(counter_min) = 0;
                };
            }
            if (id(device_mode) == 1 )
            {
                if (id(counter_min) == 5)
                {
                    id(device_mode) = 2;
                    id(relay2).turn_off();
                    id(counter_min) = 0;
                    id(regul).target_temperature_low = 30;
                    id(regul).target_temperature_high = 31;
                }
            }
      - component.update: my_display

climate:
  - platform: bang_bang
    name: "Bang Bang Climate Controller"
    sensor: temp_1
    default_target_temperature_low: 26 °C
    default_target_temperature_high: 28 °C
    id: regul
    heat_action:
      - switch.turn_on: relay1
      - component.update: my_display
    idle_action:
      - switch.turn_off: relay1
      - component.update: my_display
      